# Generated by Django 2.0.3 on 2018-04-21 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenic', '0002_auto_20180420_1327'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.ScenicArea')),
            ],
        ),
        migrations.CreateModel(
            name='AreaDiscussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.ScenicArea')),
            ],
        ),
        migrations.CreateModel(
            name='AreaScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.ScenicArea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AreaTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.ScenicArea')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_comment', to='form.Comment')),
                ('comment_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_comment', to='form.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Comment')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Discussion')),
            ],
        ),
        migrations.CreateModel(
            name='FollowArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.ScenicArea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.ScenicSpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_user', to=settings.AUTH_USER_MODEL)),
                ('user_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Article')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.ScenicSpot')),
            ],
        ),
        migrations.CreateModel(
            name='SpotDiscussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Discussion')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.ScenicSpot')),
            ],
        ),
        migrations.CreateModel(
            name='SpotScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.ScenicSpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.ScenicSpot')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VoteArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteDiscussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='spottag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Tag'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Tag'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Comment'),
        ),
        migrations.AddField(
            model_name='areatag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Tag'),
        ),
        migrations.AddField(
            model_name='areadiscussion',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Discussion'),
        ),
        migrations.AddField(
            model_name='areaarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Article'),
        ),
        migrations.AlterUniqueTogether(
            name='votediscussion',
            unique_together={('user', 'discussion')},
        ),
        migrations.AlterUniqueTogether(
            name='votearticle',
            unique_together={('user', 'article')},
        ),
        migrations.AlterUniqueTogether(
            name='spottag',
            unique_together={('spot', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='spotscore',
            unique_together={('user', 'spot')},
        ),
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together={('user_s', 'user_d')},
        ),
        migrations.AlterUniqueTogether(
            name='followspot',
            unique_together={('user', 'spot')},
        ),
        migrations.AlterUniqueTogether(
            name='followarea',
            unique_together={('user', 'area')},
        ),
        migrations.AlterUniqueTogether(
            name='articletag',
            unique_together={('article', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='areatag',
            unique_together={('area', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='areascore',
            unique_together={('user', 'area')},
        ),
    ]
