# Generated by Django 2.0.3 on 2018-05-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0005_auto_20180529_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenicarea',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
