# Generated by Django 2.0.3 on 2018-05-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0006_auto_20180529_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenicarea',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scenicspot',
            name='image',
        ),
    ]
