# Generated by Django 2.0.3 on 2018-05-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0007_auto_20180529_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenicarea',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
